### ISSUE TITLE
 Redirect User Based on Payment Status

### ISSUE THREAD

**Issue by shivikawedsyash** [shivikawedsyash/invitation#15]
As a user
I want to be redirected to a success or failure page after making a payment
So that I know the result of my transaction.

**Tasks:**

- [ ]  Write logic to redirect users to a success page if the payment is successful.
- [ ]  Write logic to redirect users to a failure page if the payment fails.

**Acceptance Criteria:**

- [ ] Users are redirected to the appropriate page (success/failure) based on payment status.

**Comment by varunvasudevan94** [comment]
I tried to keep the payment gateways simple; (without a server);
While I can redirect on payment (not sure if we can tap onto success/failure)
